Repository HXQLabs/helixque-landing, pull requests merged in 2025-10, with the labels that each got.

#44 Updated discord server insights
  app/api/github/discord/route.ts
  components/sections/cta/index.tsx
Labels: enhancement, hacktoberfest-accepted, hacktoberfest2025, hacktoberfest, hacktoberfest2025-accepted, priority: high

#50 fix: header-inconsistency
  components/common/header.tsx
Labels: hacktoberfest-accepted, hacktoberfest2025, hacktoberfest, hacktoberfest2025-accepted, UI-UX

#56 Fix hacktoberfest page
  app/api/discord/route.ts
  app/globals.css
  app/hacktoberfest/page.tsx
  components/sections/cta/index.tsx
  components/ui/aurora-text.tsx
  components/utils/clean-countdown.tsx
  components/utils/icons.tsx
Labels: hacktoberfest-accepted, hacktoberfest2025, hacktoberfest, hacktoberfest2025-accepted, priority: high, UI-UX

#59 Hotfix Navbar dark div issue
  components/common/header.tsx
Labels: hacktoberfest-accepted, hacktoberfest2025, hacktoberfest, hacktoberfest2025-accepted, priority: high, UI-UX

#78 Fix inconsistency in font sizing across UI
  components.json
  components/common/github-button-flow.tsx
  components/common/github-star-button.tsx
  components/common/vertical-separator.tsx
  components/magicui/animated-shiny-text.tsx
  components/magicui/animated-theme-toggler.tsx
  components/magicui/orbiting-circles.tsx
  components/magicui/shimmer-button.tsx
  components/sections/features/index.tsx
  components/sections/hero/index.tsx
  components/ui/cursor-cards.tsx
  components/ui/kibo-ui/announcement/index.tsx
  components/ui/particles.tsx
  public/mockup.png
Labels: enhancement, hacktoberfest-accepted, hacktoberfest2025, hacktoberfest, hacktoberfest2025-accepted, UI-UX

#82 Feat: Enable Analytics
  app/layout.tsx
  app/sticky-banner-demo/page.tsx
  package.json
Labels: hacktoberfest-accepted, hacktoberfest2025, hacktoberfest, hacktoberfest2025-accepted

#75 [FEAT]: Scroll to top button created. Closes #68
  app/layout.tsx
  components/common/scrollToTopButton.tsx
Labels: enhancement, hacktoberfest-accepted, hacktoberfest2025, hacktoberfest, hacktoberfest2025-accepted

#86 Deprecate Statistics Page
  app/api/github/route.ts
  app/apple-icon.png
  app/favicon.ico
  app/icon0.svg
  app/icon1.png
  app/manifest.json
  app/stats/page.tsx
  components/common/header.tsx
  components/common/scrollToTopButton.tsx
  components/sections/opensource/index.tsx
  components/ui/card.tsx
  components/ui/dotted-multi-line.tsx
  components/ui/dynamic-dotted-multi-line.tsx
  components/ui/dynamic-rounded-pie-chart.tsx
  components/ui/dynamic-stroke-multiple-radar-chart.tsx
  components/ui/rounded-pie-chart.tsx
  components/ui/select.tsx
  components/utils/buy-me-coffee-btn.tsx
  package.json
  public/Logo (2).png
  public/logo.svg
  public/web-app-manifest-192x192.png
  public/web-app-manifest-512x512.png
Labels: hacktoberfest-accepted, hacktoberfest2025, hacktoberfest, hacktoberfest2025-accepted

#104 Add Issue and PR Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/code_enhancement.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest2025, hacktoberfest, hacktoberfest2025-accepted
